Eco_Commerce/App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
  
]

Eco_Commerce/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decreased_cart, name='decrease'),
]

Eco_Commerce/App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name = 'App_Payment'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('pay/', views.payment, name='payment'),
    path('status/', views.complete, name='complete'),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name='purchase'),
    path('orders/', views.order_view, name='orders'),
]

Eco_Commerce/App_Shop/urls.py
from django.urls import path
from App_Shop import views
app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail')
    
]

Eco_Commerce/App_UserLog/urls.py
from django.urls import path
from App_UserLog import views

app_name = 'App_UserLog'

urlpatterns = [
    path('log/', views.user_log, name='userlog'),
    # path('user-logs/', views.UserLogList.as_view(), name='user-log-list'),
    # path('user-logs/<int:pk>/', views.UserLogDetail.as_view(), name='user-log-detail'),
]

Eco_Commerce/Eco_Commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
    path('userlog/', include('App_UserLog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Eco_Commerce/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-A-Compatible", content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" integrity="sha512-10/jx2EXwxxWqCLX/hHth/vu2KY3jCF70dCQB8TSgNjbCVAC/8vai53GfMDrO2Emgwccf2pJqxct9ehpzG+MTw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <title> {% block title_block %} E-Commerce {% endblock title_block %} </title>
      <!-- CSS BLOCK -->
      {% block css_block %}

      {% endblock %}
    <style>
      .card{
        height: 350px;
      }
      .card-product:after{
        content: "";
        display: table;
        clear: both;
        visibility: hidden;
      }
      .card-product .price-new, .card-product .price{
        margin-right: 5px;
      }
      .card-product .price-old{
        color: #999;
      }
      .card-product .img-wrap{
        border-radius: 3px 3px 0 0;
        overflow: hidden;
        position: relative;
        height: 220px;
        text-align: center;
      } 
      .card-product .img-wrap img{
        max-width: 100%;
        max-height: 100%;
        object-fit: fill;
      }
      .card-product .info-wrap{
        overflow: hidden;
        padding: 15px;
        border-top: 2px solid #eee;
      }
      .card-product .action-wrap{
        padding-top: 4px;
        margin-top: 4px;
      }
      .card-product .bottom-wrap{
        padding: 15px;
        border-top: 5px solid #eee;
      }
      .card-product .title{
        margin-top: 0px ;
      }
    </style>
  </head>
  <body>
    {% include 'navbar.html' %}
  <div class="container my-5">
    <div class="messages container mt-2">
      {% if messages %}        
        {% for message in messages %}
          <div {% if message.tags %} 
          class="alert alert-{{message.tags}} {% endif %}"
          role="alert">
            {{message}}
            <button type="submit" class="close" data-dismiss="alert" aria-label="close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}     
      {% endif %}

    </div>
    
    {% block body_block %}
      


    {% endblock body_block %}



     <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

      

  </div>


     </body>
</html>

Eco_Commerce/templates/navbar.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'App_Shop:home' %}">Mobile Store</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">         
                {% if request.user.is_authenticated   %}                                 
                <li class="nav-item"><a href="{% url 'App_UserLog:userlog' %}" class="nav-link">User Log</a></li>
                <li class="nav-item">
                 <a href="{% url 'App_Order:cart' %}" class="nav-link">
                    <i class="fa fa-shopping-cart"></i>Cart
                    <span class="badge badge-light"> {{request.user | cart_total}} </span>
                 </a>   
                </li> 
                <li class="nav-item dropdown">
                    <a href="" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie"></i> {{request.user.profile.username}} </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a href="{% url 'App_Login:profile' %}" class="dropdown-item">Profile</a>
                        <a href="{% url 'App_Payment:orders' %}" class="dropdown-item">Orders</a>
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'App_Login:logout' %}" class="dropdown-item">Logout</a>


                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'App_Login:login' %}" class="btn btn-primary">Login</a>
                </li>
                <li class="nav-item ml-2">
                    <a href="{% url 'App_Login:signup' %}" class="btn btn-primary">Signup</a>
                </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>