Eco_Commerce/App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name = 'App_Payment'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('pay/', views.payment, name='payment'),
    path('status/', views.complete, name='complete'),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name='purchase'),
    path('orders/', views.order_view, name='orders'),
]

Eco_Commerce/App_Shop/urls.py
from django.urls import path
from App_Shop import views
app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail')
    
]

Eco_Commerce/Eco_Commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
    path('userlog/', include('App_UserLog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Eco_Commerce/App_Payment/models.py
from django.db import models
from django.conf import settings
# from App_Login.models import User
# from App_Shop.models import Product
# Create your models here.

class BillingAddress(models.Model):
   user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) 
   address = models.CharField(max_length=264, blank=True)
   zipcode = models.CharField(max_length=10, blank=True)
   city = models.CharField(max_length=30, blank=True)
   country = models.CharField(max_length=20, blank=True)

   def __str__(self):
        return f"{self.user.profile.username} billing address"

#field fill up all
   def is_fully_filled(self):
        field_names = [f.name for f in self._meta.get_fields()]

        for field_name in field_names:
            value = getattr(self, field_name)

            if value is None or value == '':
                return False
        return True

   class Meta:
      verbose_name_plural = "Billing Addresses"

  

Eco_Commerce/App_Payment/forms.py
from django import forms
from App_Payment.models import BillingAddress


class BillingForm(forms.ModelForm):
    class Meta:
        model = BillingAddress
        fields = ['address', 'zipcode', 'city', 'country']

Eco_Commerce/App_Payment/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.urls import reverse
from App_Order.models import Order, Cart
from App_Payment.forms import BillingAddress
from App_Payment.forms import BillingForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# for sslcommerz payment
# import requests
# from sslcommerz_lib import SSLCOMMERZ
from decimal import Decimal
import socket
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

@login_required
def checkout(request):
    saved_address = BillingAddress.objects.get_or_create(user=request.user)
    saved_address = saved_address[0]
    form = BillingForm(instance=saved_address) #form generate from Saved Address
    if request.method == 'POST':
        form = BillingForm(request.POST, instance=saved_address)
        if form.is_valid():
            form.save()
            form = BillingForm(instance=saved_address)
            messages.success(request, f"Shipping Address Saved")
    order_qs = Order.objects.filter(user=request.user, ordered = False)     
    orderItems = order_qs[0].order_items.all()
    order_total = order_qs[0].get_totals() #Order>model>get_totals
    return render(request, 'App_Payment/checkout.html', context={'form':form, "order_items": orderItems, "order_total": order_total, "saved_address": saved_address})



@login_required
def payment(request):
    saved_address = BillingAddress.objects.get_or_create(user=request.user)
    if not saved_address[0].is_fully_filled():
        messages.info(request, f"Please complete shipping address!")
        return redirect("App_Payment:checkout")

    if not request.user.profile.is_fully_filled():
        messages.info(request, f"Complete Profile Details")
        return redirect("App_Login:profile")


        # sslcz = SSLCOMMERZ({ 'store_id': 'ecoco63c3c9f981ff6', 'store_pass': 'ecoco63c3c9f981ff6@ssl', 'issandbox': True })

    ### SSLCOMMERZ GETWAY ###   
    # store_id = "ecoco63c3c9f981ff6"
    # store_pass = "ecoco63c3c9f981ff6@ssl"
    # mypayment = SSLCSession(sslc_is_sandbox=True, sslc_store_id=store_id, sslc_store_pass=store_pass)

    # status_url = request.build_absolute_url(reverse("App_Payment:complete"))

    # mypayment.set_urls(success_url=status_url, fail_url=status_url, cancel_url=status_url, ipn_url=status_url)

    # mypayment.set_product_integration(total_amount=Decimal('20.20'), currency='BDT', product_category='clothing', product_name='demo-product', num_of_item=2, shipping_method='YES', product_profile='None')

    # mypayment.set_customer_info(name='John Doe', email='johndoe@email.com', address1='demo address', address2='demo address 2', city='Dhaka', postcode='1207', country='Bangladesh', phone='01711111111')

    # mypayment.set_shipping_info(shipping_to='demo customer', address='demo address', city='Dhaka', postcode='1209', country='Bangladesh')

    # response_data = mypayment.init_payment()

    return render(request, "App_Payment/payment.html", context={})




@csrf_exempt
def complete(request):
    if request.method == "POST" or request.method == "post":
        payment_data = request.POST
        status = payment_data['status']     
             
        # bank_tran_id = payment_data['bank_tran_id']     

        if status == 'VALID':
            val_id = payment_data['val_id']     
            tran_id = payment_data['tran_id']
            messages.success(request, f"Your Payment is completed")
            return HttpResponseRedirect(reverse("App_Payment:purchase", kwargs={"val_id":val_id,'tran_id':tran_id }))
        elif status == 'FAILED':
            messages.danger(request, f"Your Payment is failed. Please, Try Again!")    
    return render(request, "App_Payment/complete.html", context={})


# After Purchase order completion
@login_required
def purchase(request, val_id, tran_id):
    order_qs = Order.objects.filter(user=request.user, ordered = False)
    order = order_qs[0]
    orderId = tran_id
    order.ordered = True
    order.orederId = orderId
    order.paymentId = val_id 
    order.save()
    cart_items = Cart.objects.filter(user=request.user, purchased = False)
    for item in cart_items:
        item.purchased = True
        item.save()
    return HttpResponseRedirect(reverse("App_Shop:home"))


@login_required
def order_view(request):
    try:
        orders = Order.objects.filter(user=request.user, ordered = True)
        context = {"orders": orders}

    except:
        messages.warning(request, f"You don't have any active order!")
        return redirect("App_Shop:home") 
    return render(request, "App_Payment/order.html", context={})

Eco_Commerce/templates/App_Payment/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
  <div class="container mt-5">
    <h2 class="mb-3">
        Shipping Address > <span class="text-muted"> Checkout </span>
    </h2>
    <div class="row">
        <div class="col-md-9">
            <div class="card mb-5" style="height: auto;">
                <div class="card-body">
                    <form method="POST">
                        {{form|crispy}}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary float-right"> Save Address</button>
                    </form>
                </div>              
            </div>
        </div>
        <div class="col-md-3">
            <div class="card" style="height:auto">
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        {% for order_item in order_items %}
                            <li class="list-group-item">{{ order_item.item.name }} X {{order_item.quantity}}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="card-footer">
                    <span class="float-left"><strong>Order Total</strong></span>
                    <span class="float-right"><strong>&#2547;{{order_total|floatformat:2}}</strong></span>
                </div>
            </div>
            <br><br>
            {% if saved_address.is_fully_filled %}
            <a href="{% url 'App_Payment:payment' %}" class="btn btn-warning btn-sm"> Make Payment</a>
            {% else %}
            <div class="alert alert-info">
                <p>Please Fill Up All the information to make payment</p>
            </div>
            {% endif %}
        </div>
    </div>

  </div>













{% endblock body_block %}
    

Eco_Commerce/templates/App_Payment/complete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="5; {% url 'App_Shop:home' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css"
        integrity="sha512-10/jx2EXwxxWqCLX/hHth/vu2KY3jCF70dCQB8TSgNjbCVAC/8vai53GfMDrO2Emgwccf2pJqxct9ehpzG+MTw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment Status</title>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container">
        <div class="messages container mt-2">
            {% if messages %}
            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{message.tags}} {% endif %}" role="alert">
                {{message}}
                <button type="submit" class="close" data-dismiss="alert" aria-label="close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
            {% endif %}

        </div>



        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    </div>
</body>

</html>

Eco_Commerce/templates/App_Payment/order.html
{% extends 'base.html' %}
{% block body_block %}
    <div class="container mt-5">
        <h2 class="text-center"><strong>Your Orders</strong></h2>
        <div class="row">
            <div class="col-md-12">
                <div class="card mt-5" style="height: auto;">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Order Id</th>
                                    <th scope="col">Products</th>
                                    <th scope="col">Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order in orders %}
                                <tr>
                                    <th scope="row">{{forloop.counter }}</th>
                                    <td><a href="#">{{order.orederId}}</a></th>
                                    <td>
                                        {% for item in order.order_items.all %} 
                                        {{item}}
                                        <br> 
                                        {% endfor %}
                                    </td>
                                    <td><span class="badge badge-primary"></span></td>


                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-12 my-5 text-center">
                <a href="{% url 'App_Shop:home' %}">Back to Home</a>
            </div>
        </div>
    </div>
{% endblock body_block %}
    

Eco_Commerce/templates/App_Payment/payment.html
{% extends 'base.html' %}


{% block body_block %}
    
{% endblock body_block %}
    