Eco_Commerce/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decreased_cart, name='decrease'),
]

Eco_Commerce/App_Shop/urls.py
from django.urls import path
from App_Shop import views
app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail')
    
]

Eco_Commerce/Eco_Commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
    path('userlog/', include('App_UserLog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Eco_Commerce/App_Shop/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
       verbose_name_plural = "Categories"     #admin panel wont use plural form on naming it



class Product(models.Model):
    main_image = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='description')
    price = models.FloatField()
    old_price =  models.FloatField(default=0.00)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_date',]

Eco_Commerce/App_Shop/views.py
from django.shortcuts import render
# Create your views here.
from App_Shop.models import Product 
# Import Views
from django.views.generic import ListView, DetailView
#mixin
from django.contrib.auth.mixins import LoginRequiredMixin
# user log
# from django.shortcuts import render, redirect, get_object_or_404
# from django.contrib.auth.decorators import login_required
# from App_Shop.models import Product
# from App_UserLog.models import UserLog

class Home(ListView):
    model = Product
    template_name = 'App_Shop/home.html'
    # by default context value is : object_list


class ProductDetail(DetailView, LoginRequiredMixin):
    model = Product
    template_name = 'App_Shop/product_details.html'  
        # by default context value is : object

# @login_required
# def cart_add(request, product_id):
#     product = get_object_or_404(Product, id=product_id)
#     # add the product to the user's cart here
    
#     # log the user's action
#     UserLog.objects.create(user=request.user, action='added to cart', product=product)
    
#     return redirect('cart_detail')

Eco_Commerce/templates/App_Shop/home.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container my-5">
    <h2 class="my-5">Featured Products</h2>
    <div class="row">
        {% for product in object_list %}
        <div class="col-lg-3 col-md-6 col-sm-12">
            <figure class="card card-product">
                <div class="img-wrap">
                    <img src="/media/{{product.main_image}}" alt="" style="width:100%; height:300px;">
                </div>
                <figcaption class="info-wrap">
                    <h4 class="title"><a href="{% url 'App_Shop:product_detail' pk=product.pk %}">{{product.name}}</a></h4>
                    <div class="action-wrap">
                        <div class="price-wrap h5">
                            <span class="price-new"><b>&#2547; {{product.price|floatformat:2}}</b></span>
                            <span class="price-old"><del> &#2547; {{product.old_price|floatformat:2}}</del></span>
                        </div>
                    </div>
                </figcaption>
            </figure>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock body_block %}

Eco_Commerce/templates/App_Shop/product_details.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
    <div class="card">
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <div>
                            <a href=""><img src="/media/{{object.main_image}}" style="width:450px;" alt=""></a>
                        </div>
                    </div>
                </article>
            </aside>
            <aside class="col-sm-7">
                <article class="card-body p-2">
                    <h3 class="title mp-3">{{object.name}}</h3>
                    <p class="price-detail-wrap">
                        <span class="price h3 text-danger">
                            <span class="currency">BDT &#2547;</span> <span class="num">{{object.price}}
                           </span>
                        </span>
                    </p>
                    <dl class="item-property">
                        <dt>Description</dt>
                        <dd>{{object.detail_text|linebreaks}}</dd>
                    </dl>
                    <br>
                    <a href="{% url 'App_Order:add' pk=object.pk %}" class="btn btn-lg btn-outline-primary text-uppercase"><i class="fas fa-shopping-cart"></i> Add To Cart</a>
                </article>
            </aside>
        </div>
    </div>
</div>

{% endblock body_block %}